# Generated by Django 5.1.6 on 2025-06-20 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedback',
            name='prevent_self_feedback',
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('manager', models.F('employee')), _negated=True), name='prevent_self_feedback'),
        ),
    ]
