# Generated by Django 5.1.6 on 2025-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_prevent_self_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedback',
            name='prevent_self_feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='areas_to_improve',
            new_name='thoughts',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='strengths',
        ),
        migrations.AddField(
            model_name='feedback',
            name='further_action',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='manager_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
