# Generated by Django 5.1.6 on 2025-06-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_feedback_prevent_self_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='further_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
